version: '3.9'

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  mongo-auth:
    image: mongo
    # ports:
    #   - '27017:27017'
    volumes:
      - mongo-auth-vol:/data/db
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    # ports:
    #   - '5000:5000'
    volumes:
      - /usr/src/app/node_modules
      - ./auth:/usr/src/app
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRE=$JWT_EXPIRE
      - JWT_COOKIE_EXPIRE=$JWT_COOKIE_EXPIRE
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_EMAIL=$SMTP_EMAIL
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - FROM_EMAIL=$FROM_EMAIL
      - FROM_NAME=$FROM_NAME
    command:
      - npm
      - run
      - dev
  payments:
    build:
      context: ./payments
      dockerfile: Dockerfile.dev
    # ports:
    #   - '5001:5000'
    volumes:
      - /usr/src/app/node_modules
      - ./payments:/usr/src/app
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
      - STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
      - STRIPE_WEBHOOKS_SECRET=$STRIPE_WEBHOOKS_SECRET
    command:
      - npm
      - run
      - dev
volumes:
  mongo-auth-vol:
    driver: local
